// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizApp.Server.Persistence;

#nullable disable

namespace QuizApp.Server.Persistence.Migrations
{
    [DbContext(typeof(QuizAppDbContext))]
    [Migration("20260425190121_AddChallengeMode")]
    partial class AddChallengeMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActionType");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("QuizId");

                    b.HasIndex("SessionId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.Challenge", b =>
                {
                    b.Property<Guid>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CreatorTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ChallengeId");

                    b.HasIndex("PublicCode")
                        .IsUnique();

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.ChallengeAnswerOption", b =>
                {
                    b.Property<Guid>("ChallengeAnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ChallengeAnswerOptionId");

                    b.HasIndex("ChallengeQuestionId");

                    b.ToTable("ChallengeAnswerOptions");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.ChallengeQuestion", b =>
                {
                    b.Property<Guid>("ChallengeQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorSelectedOptionKey")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.HasKey("ChallengeQuestionId");

                    b.HasIndex("ChallengeId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("ChallengeQuestions");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.ChallengeSubmission", b =>
                {
                    b.Property<Guid>("ChallengeSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<string>("ParticipantName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChallengeSubmissionId");

                    b.HasIndex("ChallengeId");

                    b.ToTable("ChallengeSubmissions");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.ChallengeSubmissionAnswer", b =>
                {
                    b.Property<Guid>("ChallengeSubmissionAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("SelectedOptionKey")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("ChallengeSubmissionAnswerId");

                    b.HasIndex("ChallengeQuestionId");

                    b.HasIndex("ChallengeSubmissionId");

                    b.ToTable("ChallengeSubmissionAnswers");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CorrectNumericValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("CorrectOption")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<int>("TimeLimitSec")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("QuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OptionKey")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("QuestionOptionId");

                    b.HasIndex("QuestionId", "OptionKey")
                        .IsUnique();

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletePasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStartAllowedForEveryone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QuizOrganizerTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("QuizId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.QuizSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentQuestionIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CurrentQuestionStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("PausedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("QuestionDeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("SessionId");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.HasIndex("QuizId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.SessionResult", b =>
                {
                    b.Property<Guid>("SessionResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalCorrectResponseTimeMs")
                        .HasColumnType("bigint");

                    b.HasKey("SessionResultId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("SessionResults");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedTeamName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TeamReconnectTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("TeamId");

                    b.HasIndex("SessionId", "NormalizedTeamName")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.TeamAnswer", b =>
                {
                    b.Property<Guid>("TeamAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("SelectedOption")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamAnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TeamId");

                    b.HasIndex("SessionId", "TeamId", "QuestionId")
                        .IsUnique();

                    b.ToTable("TeamAnswers");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.Quiz", "Quiz")
                        .WithMany("AuditLogs")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuizApp.Server.Domain.Entities.QuizSession", "Session")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Quiz");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.ChallengeAnswerOption", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.ChallengeQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("ChallengeQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.ChallengeQuestion", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Questions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.ChallengeSubmission", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.ChallengeSubmissionAnswer", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.ChallengeQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("ChallengeQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizApp.Server.Domain.Entities.ChallengeSubmission", "Submission")
                        .WithMany("Answers")
                        .HasForeignKey("ChallengeSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.Question", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.QuizSession", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Sessions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.SessionResult", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.QuizSession", "Session")
                        .WithMany("Results")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizApp.Server.Domain.Entities.Team", "Team")
                        .WithOne("SessionResult")
                        .HasForeignKey("QuizApp.Server.Domain.Entities.SessionResult", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.Team", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.QuizSession", "Session")
                        .WithMany("Teams")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.TeamAnswer", b =>
                {
                    b.HasOne("QuizApp.Server.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizApp.Server.Domain.Entities.QuizSession", "Session")
                        .WithMany("Answers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizApp.Server.Domain.Entities.Team", "Team")
                        .WithMany("Answers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Session");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.Challenge", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.ChallengeQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.ChallengeSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Questions");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.QuizSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("AuditLogs");

                    b.Navigation("Results");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("QuizApp.Server.Domain.Entities.Team", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("SessionResult");
                });
#pragma warning restore 612, 618
        }
    }
}
